//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExoticRecipeWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public string recipeNameDB { get; set; }
        public int recipeOrderDB { get; set; }
        public string recipeDescriptionDB { get; set; }
        public string recipeInstructionsDB { get; set; }
        public string recipeImageDB { get; set; }
        public string recipeIngredientsDB { get; set; }
        public string recipeAuthorDB { get; set; }
    }
}
